name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-16.04

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.1.4
      with:
        node-version: ${{ matrix.node-version }}

    - name: installing dependencies
      run: npm ci
    
    - name: installing codecov
      run: npm i -g codecov
      
    - name: running lint
      run: npm run lint
    
    - name: running codecov
      run: npm run codecov

    - name: building
      run: npm run build

    - name: testing
      run: npm run test

    - name: codecov action
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
